# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: en-US

reviews:
  # generic review setting, see https://docs.coderabbit.ai/reference/configuration#reference
  # auto_apply_labels: true
  # abort_on_close: false
  high_level_summary: true
  review_status: true
  collapse_walkthrough: false
  poem: true
  sequence_diagrams: false
  slop_detection:
    label: needs_rework
  auto_review:
    enabled: true
    ignore_title_keywords:
      - WIP

  finishing_touches:
    # Docstrings | Options for generating Docstrings for your PRs/MRs.
    docstrings:
      # Docstrings | Allow CodeRabbit to generate docstrings for PRs/MRs.
      # default: true - disabled in WLED: has caused confusion in the past
      enabled: false
    unit_tests:
      # default: true - disabled in WLED: we don't have a unit test framework, this option just confuses contributors
      enabled: false
    simplify:
      enabled: true
